name: Deploy Frontend
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build container
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - name: run test
        run: docker run -e CI=true cygnetops/react-test npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: build project
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      - name: init EB CLI
        run: |
          eb init --platform ${{secrets.AWS_PLATFORM}} --region ${{secrets.AWS_DEFAULT_REGION }}
      - name: deploy to Elastic Beanstalk
        run: |
          eb deploy