name: Deploy Frontend
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout code
        uses: actions/checkout@v3
      - 
        name: login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: build image for tests
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - 
        name: run test
        run: docker run -e CI=true cygnetops/react-test npm test